name: Deploy Django Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_outputs.outputs.tag }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Dockerfile and Tag
        id: set_outputs
        run: |
          echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV
          echo "::set-output name=tag::latest"

      - name: Build Docker Image
        run: docker build -f $DOCKERFILE -t django-microservice:latest .

      - name: Save Docker Image
        run: docker save -o django-microservice.tar django-microservice:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_PUBLIC_DNS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            mkdir -p ~/django-microservice
          
      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_PUBLIC_DNS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "django-microservice.tar"
          target: "~/django-microservice"
          
      - name: Run Docker Container on Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_PUBLIC_DNS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/django-microservice
            docker load -i django-microservice.tar
            docker stop django-microservice || true
            docker rm django-microservice || true
            docker run -d --restart always -p 8000:8000 \
              --name django-microservice \
              django-microservice:latest
