name: Deploy Django Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_outputs.outputs.tag }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Dockerfile and Tag
        id: set_outputs
        run: |
          echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV
          echo "::set-output name=tag::latest"

      - name: Build Docker Image
        run: docker build -f $DOCKERFILE -t django-microservice:latest .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_PUBLIC_DNS }} >> ~/.ssh/known_hosts

      - name: Copy Files to Server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_PUBLIC_DNS }}:~/django-microservice

      - name: Build and Run Docker Container on Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_PUBLIC_DNS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/django-microservice
            docker stop django-microservice || true
            docker rm django-microservice || true
            docker build -t django-microservice:latest .
            docker run -d --restart always -p 8000:8000 \
            --name django-microservice \
            django-microservice:latest
