name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-microservice
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Run container for testing
        run: |
          docker run -d -p 8000:8000 --name test_container $IMAGE_NAME:$IMAGE_TAG

      - name: Wait for container to start
        run: sleep 10

      - name: Test API endpoint
        run: |
          curl -X POST http://localhost:8000/api/process/ \
            -H "Content-Type: application/json" \
            -d '{"email": "test@example.com", "message": "Hello from CI!"}'

      - name: Stop and remove test container
        if: always()
        run: docker rm -f test_container
