name: Deploy Django Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_outputs.outputs.tag }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Dockerfile and Tag
        id: set_outputs
        run: |
          echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV
          echo "::set-output name=tag::latest"

      - name: Login to Docker Hub
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build Docker Image
        run: docker build -f $DOCKERFILE -t ${{ secrets.DOCKER_REPO }}:${{ env.TAG }} .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_REPO }}:${{ env.TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Server via SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_PUBLIC_DNS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
            docker pull ${{ secrets.DOCKER_REPO }}:${{ needs.build.outputs.tag }}
            docker stop django-microservice || true
            docker rm django-microservice || true
            docker run -d --restart always -p 8000:8000 \
            --name django-microservice \
            ${{ secrets.DOCKER_REPO }}:${{ needs.build.outputs.tag }}
